#!/usr/bin/env python3

# From delta to sync NCR dataBase from azura 

# This is a test to Azura tools syncronisation of a database in python, if this is a good tools maybe it will be add on official devel branche 

# Help for azura pm 
def help () :
  print ("azura sync : syncronyse database from NCR") 
  print ("azura compile : compile the pkgfile")
  print ("azura remove : remove the package")

# Function compile 
def compile () : 
  print ("Verification de la présence des principaux outils de cards nécessaire pour cette opération")
  print (" Tous les outils de cards.devel sont présents, début de l'opération")

# function update_database 
def update_database 
  print ("Mise à jour de la base de donnée")

# If error of syntax show help
  
# function 
def main 
  if args == "help":
        help(args[1])
        
  
  
  # End of file (test in python language)
  
  
  
