#! /bin/bash
# Azura : A cards complement build for manage package from the NCR( Nutyx Community Repository ).

# It's devel by Delta, an official member of the NuTyX Devel Team for the community 

# Function help 
function help () {
        echo -e " azura compile : compile a software from its pkgfile "
        echo -e " azura remove : remove the package "
        echo -e " azura info : show the information about the package "
}

# Add a package from the NCR 
function compile () { 
        echo " Verification of the cards devel utils "
        echo " All cards devel programs are installed, start the installation process, please wait "
	echo "Êtes-vous sûr de vouloir poursuivre [O/N] : "
}
	

# Remove a package from the NCR 
function remove () { 

# Show information about the package 
function info () {

# Search a package in the NCR 
function search () { 


# If error on syntax show help 
	if [[ $# = 0 ]];then
		help
}

# Function main 
function main () {
        if [ "$OPT_MODE" = "compile" ]; then
               compile 
	if [[ $# = 0 ]];then
		help
	       
        elif [ "$OPT_MODE" = "help" ]; then
	        help
main $@

# End of Azura code.
# Thanks to all the contributors 
